#!/bin/sh
indent \
-T gchar \
-T guint16 \
-T guint32 \
-T guint8 \
-T GApplication \
-T GApplicationClass \
-T GAsyncResult \
-T GError \
-T GIOStream \
-T GNetworkAddress \
-T GObject \
-T GObjectClass \
-T GSocketClient \
-T GSocketClientEvent \
-T GSocketConnectable \
-T GTlsCertificate \
-T GTlsConnection \
-T MumbleApplication \
-T MumbleApplicationClass \
-T MumbleNetwork \
-T MumbleNetworkClass \
-T MumblePacketHeader \
-nut "$@"
